"use client";

import { useState, useRef, useCallback } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  LogOut, Upload, Download, Send, Mail, Settings2, CheckCircle2,
  XCircle, Loader2, Eye, FileText, ChevronDown, ChevronUp, AlertTriangle,
} from "lucide-react";
import type { SessionUser } from "@/lib/auth";
import { jsPDF } from "jspdf";

interface Template { id: string; title: string; description: string; fields: string[]; }
interface Props {
  session: SessionUser;
  templates: Template[];
  selectedTemplateId: string | null;
  initialContent: string | null;
  initialFields: string[];
}
interface SmtpConfig {
  host: string; port: number; secure: boolean; user: string; pass: string; from: string;
}
interface SendResult { email: string; status: "pending" | "sending" | "ok" | "error"; error?: string; }

const NAV_TABS = [
  { href: "/dashboard", label: "Documents" },
  { href: "/dashboard/templates", label: "Templates" },
  { href: "/dashboard/merge", label: "Mail Merge" },
];

const DEFAULT_SMTP: SmtpConfig = { host: "", port: 587, secure: false, user: "", pass: "", from: "" };
const LS_SMTP = "dockaro:smtp-config";

function parseCSV(text: string): Record<string, string>[] {
  const lines = text.trim().split(/\r?\n/);
  if (lines.length < 2) return [];
  const headers = lines[0].split(",").map((h) => h.trim().replace(/^"|"$/g, ""));
  return lines.slice(1)
    .filter((l) => l.trim())
    .map((line) => {
      const vals = line.split(",").map((v) => v.trim().replace(/^"|"$/g, ""));
      const row: Record<string, string> = {};
      headers.forEach((h, i) => { row[h] = vals[i] ?? ""; });
      return row;
    });
}

function applyMerge(template: string, row: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, k) => row[k] ?? `{{${k}}}`);
}

/** Extract plain text from Univer IDocumentData JSON */
function extractDocText(contentJson: string | null): string {
  if (!contentJson) return "";
  try {
    const data = JSON.parse(contentJson);
    const stream: string = data?.body?.dataStream ?? "";
    return stream
      .replace(/\r/g, "\n")
      .replace(/[\x00-\x0c\x0e-\x1f]/g, "")
      .replace(/\t/g, "  ")
      .trim();
  } catch {
    return contentJson;
  }
}

/** Generate a professional PDF from merged text */
function generatePdf(mergedText: string, recipientName: string, senderName: string): string {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 20;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;

  // Header bar
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 0, pageW, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(senderName, margin, 11);

  // Date top right
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" }), pageW - margin, 11, { align: "right" });

  // Body text
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  let y = 30;
  const lines = mergedText.split("\n");
  for (const rawLine of lines) {
    const wrapped = doc.splitTextToSize(rawLine || " ", maxW) as string[];
    for (const wl of wrapped) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.text(wl, margin, y);
      y += 6;
    }
    if (!rawLine.trim()) y += 2; // blank line extra spacing
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, footerY - 4, pageW - margin, footerY - 4);
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DocKaro · dockaro.com", margin, footerY);
  doc.text(`Page 1`, pageW - margin, footerY, { align: "right" });

  return doc.output("datauristring").split(",")[1]; // base64
}

function buildEmailHtml(mergedText: string, fromName: string): string {
  const lines = mergedText.split("\n");
  const bodyHtml = lines
    .map((l) => l.trim() ? `<p style="margin:0 0 8px">${l.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</p>` : `<br>`)
    .join("\n");
  return `<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;font-size:14px;color:#222;max-width:640px;margin:auto;padding:24px">
<div style="border-top:4px solid #3b82f6;padding-top:20px">
${bodyHtml}
</div>
<hr style="margin:28px 0;border:none;border-top:1px solid #e5e7eb">
<p style="font-size:11px;color:#9ca3af">Sent via <a href="https://dockaro.com" style="color:#3b82f6">DocKaro</a> by ${fromName.replace(/</g,"&lt;")}</p>
</body></html>`;
}

export default function MergeClient({ session, templates, selectedTemplateId, initialContent, initialFields }: Props) {
  const router = useRouter();
  const [selectedId, setSelectedId] = useState(selectedTemplateId ?? "");
  const [csvRows, setCsvRows] = useState<Record<string, string>[]>([]);
  const [csvHeaders, setCsvHeaders] = useState<string[]>([]);
  const [emailCol, setEmailCol] = useState("");
  const [nameCol, setNameCol] = useState("");
  const [subject, setSubject] = useState("Important document for {{first_name}}");
  const [fromName, setFromName] = useState(session.name);
  const [showSmtp, setShowSmtp] = useState(false);
  const [smtpCfg, setSmtpCfg] = useState<SmtpConfig>(() => {
    try { return JSON.parse(localStorage.getItem(LS_SMTP) ?? "{}") as SmtpConfig || DEFAULT_SMTP; } catch { return DEFAULT_SMTP; }
  });
  const [smtpStatus, setSmtpStatus] = useState<"idle" | "testing" | "ok" | "error">("idle");
  const [smtpError, setSmtpError] = useState("");
  const [preview, setPreview] = useState<{ text: string; html: string } | null>(null);
  const [sending, setSending] = useState(false);
  const [results, setResults] = useState<SendResult[]>([]);
  const [showResults, setShowResults] = useState(false);
  const abortRef = useRef(false);

  const currentTemplate = templates.find((t) => t.id === selectedId);
  const contentText = extractDocText(initialContent);

  function saveSmtp(cfg: SmtpConfig) {
    setSmtpCfg(cfg);
    try { localStorage.setItem(LS_SMTP, JSON.stringify(cfg)); } catch {}
  }

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    router.push("/"); router.refresh();
  }

  function handleCsvUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      const text = ev.target?.result as string;
      const rows = parseCSV(text);
      setCsvRows(rows);
      const headers = rows.length ? Object.keys(rows[0]) : [];
      setCsvHeaders(headers);
      // Auto-detect email column
      const emailGuess = headers.find((h) => /^email/i.test(h)) ?? headers.find((h) => /email/i.test(h)) ?? "";
      const nameGuess = headers.find((h) => /^(name|full.?name|first.?name)/i.test(h)) ?? "";
      setEmailCol(emailGuess);
      setNameCol(nameGuess);
    };
    reader.readAsText(file);
  }

  function handleSelectTemplate(id: string) {
    setSelectedId(id);
    router.push(`/dashboard/merge?template=${id}`, { scroll: false });
    setPreview(null);
  }

  function runPreview() {
    if (!csvRows.length) return;
    const row = csvRows[0];
    const text = applyMerge(contentText || `Dear {{first_name}},\n\nThank you for your interest.\n\nRegards,\n${fromName}`, row);
    const html = buildEmailHtml(text, fromName);
    setPreview({ text, html });
  }

  async function testSmtp() {
    setSmtpStatus("testing"); setSmtpError("");
    const res = await fetch("/api/v1/merge/test-smtp", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ smtp: smtpCfg }),
    });
    const data = await res.json();
    if (res.ok) { setSmtpStatus("ok"); }
    else { setSmtpStatus("error"); setSmtpError(data.error ?? "Connection failed"); }
  }

  function downloadAllPdfs() {
    if (!csvRows.length) return;
    const templateText = contentText || `Dear {{first_name}},\n\nThank you.\n\nRegards,\n${fromName}`;
    csvRows.forEach((row, i) => {
      const merged = applyMerge(templateText, row);
      const base64 = generatePdf(merged, row[nameCol] || `Recipient ${i + 1}`, fromName);
      const link = document.createElement("a");
      link.href = `data:application/pdf;base64,${base64}`;
      link.download = `${currentTemplate?.title ?? "document"}_${i + 1}.pdf`;
      link.click();
    });
  }

  const sendAll = useCallback(async () => {
    if (!csvRows.length || !emailCol || !smtpCfg.host || !smtpCfg.user) return;
    abortRef.current = false;
    setSending(true);
    setShowResults(true);
    const templateText = contentText || `Dear {{first_name}},\n\nThank you.\n\nRegards,\n${fromName}`;
    const initial: SendResult[] = csvRows.map((row) => ({ email: row[emailCol] ?? "(no email)", status: "pending" }));
    setResults(initial);

    for (let i = 0; i < csvRows.length; i++) {
      if (abortRef.current) break;
      const row = csvRows[i];
      const email = row[emailCol]?.trim();
      if (!email) {
        setResults((r) => { const n = [...r]; n[i] = { email: "(empty)", status: "error", error: "No email address" }; return n; });
        continue;
      }
      setResults((r) => { const n = [...r]; n[i] = { ...n[i], status: "sending" }; return n; });

      const mergedText = applyMerge(templateText, row);
      const pdfBase64 = generatePdf(mergedText, row[nameCol] || "", fromName);
      const mergedSubject = applyMerge(subject, row);
      const bodyHtml = buildEmailHtml(mergedText, fromName);
      const filename = `${currentTemplate?.title ?? "document"}.pdf`;

      try {
        const res = await fetch("/api/v1/merge/send", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ to: email, toName: row[nameCol] || "", subject: mergedSubject, bodyHtml, fromName, pdfBase64, pdfFilename: filename, smtp: smtpCfg }),
        });
        const data = await res.json();
        if (res.ok) {
          setResults((r) => { const n = [...r]; n[i] = { email, status: "ok" }; return n; });
        } else {
          setResults((r) => { const n = [...r]; n[i] = { email, status: "error", error: data.error }; return n; });
        }
      } catch (err) {
        setResults((r) => { const n = [...r]; n[i] = { email, status: "error", error: (err as Error).message }; return n; });
      }
      // small delay to avoid rate limits
      if (i < csvRows.length - 1) await new Promise((r) => setTimeout(r, 400));
    }
    setSending(false);
  }, [csvRows, emailCol, nameCol, subject, fromName, contentText, smtpCfg, currentTemplate]);

  const sentOk = results.filter((r) => r.status === "ok").length;
  const sentFail = results.filter((r) => r.status === "error").length;
  const smtpReady = smtpCfg.host && smtpCfg.user && smtpCfg.pass;

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-border/80 bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-6">
          <Link href="/" className="flex items-center gap-2 font-semibold tracking-tight text-foreground">
            <span className="flex h-7 w-7 items-center justify-center rounded-md bg-accent text-sm font-bold text-white">D</span>
            DocKaro
          </Link>
          <div className="flex items-center gap-4">
            <span className="hidden text-sm text-muted sm:block">{session.email}</span>
            <button onClick={logout} className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm text-muted transition-colors hover:bg-white/5 hover:text-foreground">
              <LogOut size={14} /> Sign out
            </button>
          </div>
        </div>
        <div className="mx-auto max-w-6xl px-6">
          <div className="flex gap-6 text-sm">
            {NAV_TABS.map((tab) => (
              <Link key={tab.href} href={tab.href} className={`border-b-2 py-3 transition-colors ${tab.href === "/dashboard/merge" ? "border-accent text-foreground" : "border-transparent text-muted hover:text-foreground"}`}>{tab.label}</Link>
            ))}
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-10">
        <div className="mb-8">
          <h1 className="text-2xl font-semibold text-foreground">Mail Merge & PDF Sender</h1>
          <p className="mt-1 text-sm text-muted">Generate personalised PDFs and send them directly to each recipient's inbox</p>
        </div>

        {/* Step 1: Template */}
        <Step number={1} title="Choose a template">
          {templates.length === 0 ? (
            <p className="text-sm text-muted">No templates yet. <Link href="/dashboard/templates" className="text-accent hover:underline">Create one first</Link>.</p>
          ) : (
            <>
              <select value={selectedId} onChange={(e) => handleSelectTemplate(e.target.value)}
                className="w-full rounded-lg border border-border bg-background px-3 py-2.5 text-sm text-foreground focus:border-accent focus:outline-none">
                <option value="">— Select a template —</option>
                {templates.map((t) => <option key={t.id} value={t.id}>{t.title}{t.description ? ` — ${t.description}` : ""}</option>)}
              </select>
              {currentTemplate?.fields.length ? (
                <div className="mt-3 flex flex-wrap items-center gap-1.5 text-xs">
                  <span className="text-muted">Merge fields:</span>
                  {currentTemplate.fields.map((f) => (
                    <code key={f} className="rounded bg-accent/10 px-1.5 py-0.5 text-accent">{`{{${f}}}`}</code>
                  ))}
                </div>
              ) : null}
            </>
          )}
        </Step>

        {/* Step 2: CSV */}
        <Step number={2} title="Upload recipient CSV">
          <label className="flex cursor-pointer flex-col items-center gap-2 rounded-xl border border-dashed border-border px-6 py-8 text-center transition-colors hover:border-accent/50">
            <Upload size={20} className="text-muted" />
            <span className="text-sm font-medium text-foreground">
              {csvRows.length > 0 ? `${csvRows.length} recipient${csvRows.length === 1 ? "" : "s"} loaded` : "Click to upload CSV"}
            </span>
            <span className="text-xs text-muted">Must include a column for email address. Merge fields like {"{{"+"first_name"+"}}"} map to column headers.</span>
            <input type="file" accept=".csv,text/csv" className="hidden" onChange={handleCsvUpload} />
          </label>
          {csvRows.length > 0 && (
            <div className="mt-4 overflow-x-auto rounded-lg border border-border">
              <table className="w-full text-xs">
                <thead className="bg-surface">
                  <tr>{csvHeaders.map((h) => <th key={h} className="px-3 py-2 text-left font-medium text-muted">{h}</th>)}</tr>
                </thead>
                <tbody>
                  {csvRows.slice(0, 3).map((row, i) => (
                    <tr key={i} className="border-t border-border">
                      {csvHeaders.map((h) => <td key={h} className="px-3 py-2 text-foreground">{row[h]}</td>)}
                    </tr>
                  ))}
                </tbody>
              </table>
              {csvRows.length > 3 && <p className="px-3 py-2 text-xs text-muted">…and {csvRows.length - 3} more rows</p>}
            </div>
          )}
        </Step>

        {/* Step 3: Email config */}
        <Step number={3} title="Configure email">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium text-muted">Email column</label>
              <select value={emailCol} onChange={(e) => setEmailCol(e.target.value)}
                className="rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:border-accent focus:outline-none">
                <option value="">— select column —</option>
                {csvHeaders.map((h) => <option key={h} value={h}>{h}</option>)}
              </select>
            </div>
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium text-muted">Name column (optional)</label>
              <select value={nameCol} onChange={(e) => setNameCol(e.target.value)}
                className="rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:border-accent focus:outline-none">
                <option value="">— none —</option>
                {csvHeaders.map((h) => <option key={h} value={h}>{h}</option>)}
              </select>
            </div>
            <div className="flex flex-col gap-1.5 sm:col-span-2">
              <label className="text-xs font-medium text-muted">Subject line <span className="text-muted/60">(merge fields work here too)</span></label>
              <input value={subject} onChange={(e) => setSubject(e.target.value)}
                className="rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:border-accent focus:outline-none" />
            </div>
            <div className="flex flex-col gap-1.5">
              <label className="text-xs font-medium text-muted">From name</label>
              <input value={fromName} onChange={(e) => setFromName(e.target.value)}
                className="rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground focus:border-accent focus:outline-none" />
            </div>
          </div>

          {/* SMTP settings collapsible */}
          <button onClick={() => setShowSmtp((v) => !v)}
            className="mt-4 flex items-center gap-2 text-xs font-medium text-muted transition-colors hover:text-foreground">
            <Settings2 size={13} />
            SMTP settings
            {showSmtp ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
            {smtpReady && <span className="ml-1 rounded bg-green-500/15 px-1.5 py-0.5 text-green-400">configured</span>}
          </button>

          {showSmtp && (
            <div className="mt-3 grid gap-3 rounded-xl border border-border bg-surface/50 p-4 sm:grid-cols-2">
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted">SMTP host</label>
                <input value={smtpCfg.host} onChange={(e) => saveSmtp({ ...smtpCfg, host: e.target.value })}
                  placeholder="smtp.gmail.com" className="rounded border border-border bg-background px-2 py-1.5 text-xs text-foreground focus:border-accent focus:outline-none" />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted">Port</label>
                <input type="number" value={smtpCfg.port} onChange={(e) => saveSmtp({ ...smtpCfg, port: Number(e.target.value) })}
                  className="rounded border border-border bg-background px-2 py-1.5 text-xs text-foreground focus:border-accent focus:outline-none" />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted">Username / email</label>
                <input value={smtpCfg.user} onChange={(e) => saveSmtp({ ...smtpCfg, user: e.target.value })}
                  placeholder="you@gmail.com" className="rounded border border-border bg-background px-2 py-1.5 text-xs text-foreground focus:border-accent focus:outline-none" />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted">Password / app password</label>
                <input type="password" value={smtpCfg.pass} onChange={(e) => saveSmtp({ ...smtpCfg, pass: e.target.value })}
                  placeholder="••••••••" className="rounded border border-border bg-background px-2 py-1.5 text-xs text-foreground focus:border-accent focus:outline-none" />
              </div>
              <div className="flex flex-col gap-1">
                <label className="text-xs text-muted">From address <span className="text-muted/60">(if different from username)</span></label>
                <input value={smtpCfg.from} onChange={(e) => saveSmtp({ ...smtpCfg, from: e.target.value })}
                  placeholder="noreply@yourcompany.com" className="rounded border border-border bg-background px-2 py-1.5 text-xs text-foreground focus:border-accent focus:outline-none" />
              </div>
              <div className="flex items-end gap-2">
                <label className="flex items-center gap-1.5 text-xs text-muted">
                  <input type="checkbox" checked={smtpCfg.secure} onChange={(e) => saveSmtp({ ...smtpCfg, secure: e.target.checked })} />
                  SSL/TLS (port 465)
                </label>
              </div>
              <div className="sm:col-span-2">
                <button onClick={testSmtp} disabled={smtpStatus === "testing" || !smtpCfg.host}
                  className="flex items-center gap-1.5 rounded-lg border border-border px-3 py-1.5 text-xs transition-colors hover:bg-white/5 disabled:opacity-40">
                  {smtpStatus === "testing" ? <Loader2 size={12} className="animate-spin" /> : <Settings2 size={12} />}
                  Test connection
                </button>
                {smtpStatus === "ok" && <p className="mt-1.5 flex items-center gap-1 text-xs text-green-400"><CheckCircle2 size={12} /> SMTP connected</p>}
                {smtpStatus === "error" && <p className="mt-1.5 flex items-center gap-1 text-xs text-red-400"><XCircle size={12} /> {smtpError}</p>}
                <p className="mt-2 text-xs text-muted/60">
                  Gmail: use an <a href="https://myaccount.google.com/apppasswords" target="_blank" rel="noopener" className="text-accent hover:underline">app password</a>, not your main password.
                  For Outlook use smtp.office365.com:587. SMTP settings are saved in your browser only.
                </p>
              </div>
            </div>
          )}
        </Step>

        {/* Actions */}
        <div className="mt-6 flex flex-wrap gap-3">
          <button onClick={runPreview} disabled={!selectedId || !csvRows.length}
            className="flex items-center gap-2 rounded-xl border border-border bg-surface px-5 py-3 text-sm font-medium text-foreground transition-colors hover:border-accent/50 hover:bg-accent/5 disabled:opacity-40">
            <Eye size={15} /> Preview first row
          </button>
          <button onClick={downloadAllPdfs} disabled={!csvRows.length}
            className="flex items-center gap-2 rounded-xl border border-border bg-surface px-5 py-3 text-sm font-medium text-foreground transition-colors hover:border-accent/50 hover:bg-accent/5 disabled:opacity-40">
            <Download size={15} /> Download {csvRows.length} PDF{csvRows.length === 1 ? "" : "s"}
          </button>
          <button
            onClick={sending ? () => { abortRef.current = true; } : sendAll}
            disabled={!csvRows.length || !emailCol || !smtpReady}
            className={`flex items-center gap-2 rounded-xl px-5 py-3 text-sm font-medium text-white transition-opacity disabled:opacity-40 ${sending ? "bg-red-500 hover:opacity-90" : "bg-accent hover:opacity-90"}`}
            title={!smtpReady ? "Configure SMTP settings first" : ""}
          >
            {sending ? (
              <><Loader2 size={15} className="animate-spin" /> Stop sending</>
            ) : (
              <><Send size={15} /> Send to {csvRows.length} recipient{csvRows.length === 1 ? "" : "s"}</>
            )}
          </button>
        </div>

        {!smtpReady && csvRows.length > 0 && (
          <div className="mt-3 flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-xs text-amber-400">
            <AlertTriangle size={13} />
            Configure SMTP settings above to enable email sending. PDF download works without SMTP.
          </div>
        )}

        {/* Results */}
        {results.length > 0 && (
          <div className="mt-6 rounded-xl border border-border bg-surface p-5">
            <div className="mb-3 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <h2 className="text-sm font-semibold text-foreground">Send progress</h2>
                <span className="text-xs text-green-400">{sentOk} sent</span>
                {sentFail > 0 && <span className="text-xs text-red-400">{sentFail} failed</span>}
              </div>
              <button onClick={() => setShowResults((v) => !v)} className="text-xs text-muted hover:text-foreground">
                {showResults ? "Hide" : "Show"} details
              </button>
            </div>
            {/* Progress bar */}
            <div className="mb-4 h-2 w-full overflow-hidden rounded-full bg-border">
              <div
                className="h-full rounded-full bg-accent transition-all duration-300"
                style={{ width: `${results.length ? ((sentOk + sentFail) / results.length) * 100 : 0}%` }}
              />
            </div>
            {showResults && (
              <div className="max-h-64 overflow-y-auto space-y-1">
                {results.map((r, i) => (
                  <div key={i} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs">
                    {r.status === "pending" && <div className="h-3 w-3 rounded-full border border-border" />}
                    {r.status === "sending" && <Loader2 size={12} className="animate-spin text-accent" />}
                    {r.status === "ok" && <CheckCircle2 size={12} className="text-green-400" />}
                    {r.status === "error" && <XCircle size={12} className="text-red-400" />}
                    <span className={r.status === "ok" ? "text-foreground" : r.status === "error" ? "text-red-400" : "text-muted"}>
                      {r.email}
                    </span>
                    {r.error && <span className="ml-auto text-red-400/70">{r.error}</span>}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Preview pane */}
        {preview && (
          <div className="mt-6 rounded-xl border border-border bg-surface p-5">
            <div className="mb-4 flex items-center gap-3">
              <h2 className="text-sm font-semibold text-foreground">Preview — row 1</h2>
              <div className="flex gap-2">
                <span className="rounded bg-accent/10 px-2 py-0.5 text-xs text-accent flex items-center gap-1"><FileText size={10} /> PDF</span>
                <span className="rounded bg-green-500/10 px-2 py-0.5 text-xs text-green-400 flex items-center gap-1"><Mail size={10} /> Email</span>
              </div>
            </div>
            <div className="rounded-lg border border-border bg-background p-4">
              <pre className="whitespace-pre-wrap text-sm text-foreground leading-relaxed">{preview.text}</pre>
            </div>
            <div className="mt-3 text-xs text-muted">
              Subject: <span className="text-foreground">{applyMerge(subject, csvRows[0] ?? {})}</span>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

function Step({ number, title, children }: { number: number; title: string; children: React.ReactNode }) {
  return (
    <div className="mb-5 rounded-xl border border-border bg-surface p-5">
      <div className="mb-4 flex items-center gap-3">
        <span className="flex h-6 w-6 items-center justify-center rounded-full bg-accent text-xs font-bold text-white">{number}</span>
        <h2 className="text-sm font-semibold text-foreground">{title}</h2>
      </div>
      {children}
    </div>
  );
}
